In [2]:
import numpy as np

# Universal functions: Fast Elements wise  Array Functions

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
sqrt=np.sqrt(arr)
sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x=np.random.randn(10)
y=np.random.randn(10)

In [7]:
np.maximum(x,y)

array([ 0.43631871, -0.93521691, -0.12897135,  1.63216759,  0.97623701,
        0.36208477,  1.36514913,  0.21870416,  1.56753225, -0.43628404])

In [8]:
arr=np.random.randn(7)*5


In [9]:
arr

array([ -1.60831519,   9.83967959,   1.48267856,  -4.69191259,
        -3.39284557,  -5.80695092, -15.90510774])

In [13]:
remainder,whole_part=np.modf(arr) #returns the fractional and integral part of a floating array

In [14]:
remainder

array([-0.60831519,  0.83967959,  0.48267856, -0.69191259, -0.39284557,
       -0.80695092, -0.90510774])

In [15]:
whole_part

array([ -1.,   9.,   1.,  -4.,  -3.,  -5., -15.])

In [16]:
np.sqrt(arr)

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 3.13682636, 1.21765289,        nan,        nan,
              nan,        nan])

In [17]:
arr

array([ -1.60831519,   9.83967959,   1.48267856,  -4.69191259,
        -3.39284557,  -5.80695092, -15.90510774])

In [63]:
arr=np.random.randn(10)
arr1=np.arange(20,30)
arr
arr1=arr1-22
arr1=np.round(arr1)
print(arr)
arr1

[-0.31327737  0.25387195  1.26229551  1.37309266  1.18122277 -0.50602229
  2.56184177 -1.11952421 -0.17116226 -1.07475091]


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [56]:
x=np.abs(arr1) #returns the absolute value

In [57]:
x

array([2, 1, 0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
x=np.fabs(arr) #returns absolute for floating point and complex values

In [59]:
x

array([0.78179866, 1.36013289, 1.34980952, 0.48968427, 1.15995362,
       1.58904693, 0.67355243, 1.54933296, 2.16967501, 1.69208075])

In [69]:
np.square(arr1) #compute the square which is equivalent to x**2

array([ 4,  1,  0,  1,  4,  9, 16, 25, 36, 49])

In [70]:
np.exp(arr) #computes the exponentional of each elements

array([ 0.73104711,  1.28900674,  3.53352343,  3.94754022,  3.25835599,
        0.60288893, 12.95966402,  0.32643507,  0.84268483,  0.34138278])

In [73]:
#Computing Logarithms
np.log(np.abs(arr1)) #log(base e)

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([0.69314718, 0.        ,       -inf, 0.        , 0.69314718,
       1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [74]:
np.log10(arr1) #log base 10

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.
/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([       nan,        nan,       -inf, 0.        , 0.30103   ,
       0.47712125, 0.60205999, 0.69897   , 0.77815125, 0.84509804])

In [76]:
np.log2(arr) #log base 2

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([        nan, -1.97782709,  0.33604969,  0.45742898,  0.24028107,
               nan,  1.35718137,         nan,         nan,         nan])

In [77]:
np.log1p(np.arange(10)) #log (1+x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [78]:
arr1

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [79]:
np.sign(arr1) #computes the sign of each elements where 1(Positive), 0(Zero), -1(negative) 

array([-1, -1,  0,  1,  1,  1,  1,  1,  1,  1])

In [84]:
arr1=np.random.rand(10)*10
arr1

array([4.70376153, 5.34775413, 7.99504729, 8.78073614, 5.22876786,
       7.07957641, 8.90018214, 4.8112486 , 2.07805689, 7.40550698])

In [88]:
np.ceil(arr1) #computes the ceil value of all the elemets, converting to the least minimun value of ranging from
#respective value to the maximum infinite value

array([5., 6., 8., 9., 6., 8., 9., 5., 3., 8.])

In [87]:
arr1.dtype

dtype('float64')

In [89]:
np.floor(arr1) #computes the floor value of all the elemets, converting to the maximum value of ranging from
#0 to the respective value

array([4., 5., 7., 8., 5., 7., 8., 4., 2., 7.])

In [92]:
print(arr1)
np.rint(arr1) #rounding the value to the nearest integer value of the data type, reserving the data type

[4.70376153 5.34775413 7.99504729 8.78073614 5.22876786 7.07957641
 8.90018214 4.8112486  2.07805689 7.40550698]


array([5., 5., 8., 9., 5., 7., 9., 5., 2., 7.])

In [97]:
x=np.sqrt(arr)
x

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.50385707, 1.12351925, 1.17179036, 1.08684073,
              nan, 1.60057545,        nan,        nan,        nan])

In [98]:
np.isnan(x) #returning the boolean value indicating that whether that the array has any nan(Not a Number) or not

array([ True, False, False, False, False,  True, False,  True,  True,
        True])

In [112]:
arr2=np.arange(-5,10)

In [113]:
arr2

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [114]:
x=np.log10(arr2)
x

/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.
/home/usman/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
             -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [115]:
np.isfinite(x) #returns whether the value if finite or not

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [116]:
np.isinf(x) #returns whether the value if infinite or not

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False])

In [117]:
np.isnan(x)

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

#  Trignometric Functions

In [121]:
x=np.cos(np.arange(10,20))
x

array([-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [122]:
x=np.cosh(np.arange(10.20))
x

array([1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
       2.73082328e+01, 7.42099485e+01, 2.01715636e+02, 5.48317035e+02,
       1.49047916e+03, 4.05154203e+03, 1.10132329e+04])

In [123]:
x=np.sin(np.arange(10,20))
x

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [124]:
x=np.sinh(np.arange(10,20))
x

array([1.10132329e+04, 2.99370708e+04, 8.13773957e+04, 2.21206696e+05,
       6.01302142e+05, 1.63450869e+06, 4.44305526e+06, 1.20774764e+07,
       3.28299846e+07, 8.92411505e+07])

In [125]:
x=np.tan(np.arange(10,20))
x

array([ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
        7.24460662e+00, -8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
       -1.13731371e+00,  1.51589471e-01])

In [126]:
x=np.tanh(np.arange(10,20))
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [171]:
#inverse Trignometric Functions
a=np.random.rand(20)
print(a)
x=np.arccos(a)
x

[0.47221172 0.13744174 0.89652579 0.22448751 0.45413083 0.10043151
 0.01979851 0.36824442 0.17251979 0.8313606  0.77335899 0.6071003
 0.97321565 0.91725793 0.0421211  0.61537492 0.98720084 0.69354286
 0.99911897 0.98281915]


array([1.07899814, 1.43291815, 0.45893275, 1.34437924, 1.09939993,
       1.47019521, 1.55099652, 1.19367629, 1.39740908, 0.58924482,
       0.68667381, 0.91838998, 0.23196886, 0.40965589, 1.52866277,
       0.9079348 , 0.16016588, 0.80440104, 0.04197987, 0.1856355 ])

In [172]:
x=np.arcsin(a)
x

array([0.49179818, 0.13787818, 1.11186358, 0.22641709, 0.4713964 ,
       0.10060112, 0.01979981, 0.37712004, 0.17338725, 0.98155151,
       0.88412252, 0.65240634, 1.33882747, 1.16114044, 0.04213356,
       0.66286153, 1.41063044, 0.76639529, 1.52881646, 1.38516083])

In [173]:
x=np.arccosh(np.random.randint(1,19,size=[10]))
x

array([3.52549435, 3.40008441, 2.47788873, 3.33092655, 3.46475791,
       1.76274717, 3.0889699 , 3.0889699 , 3.25661395, 3.0889699 ])

In [176]:
x=np.arcsinh(np.random.randint(1,19,size=[10]))
x

array([3.0931022 , 1.81844646, 2.49177985, 3.0931022 , 2.31243834,
       2.77647228, 2.77647228, 2.31243834, 2.49177985, 2.99822295])

In [178]:
x=np.arctan(np.random.rand(20))
x

array([0.68149807, 0.7047265 , 0.74021083, 0.73050555, 0.36123926,
       0.32591071, 0.60702046, 0.03742578, 0.49259795, 0.71363473,
       0.30988963, 0.70140907, 0.73895349, 0.31722252, 0.63026086,
       0.02988317, 0.38084976, 0.31925391, 0.29499132, 0.0543975 ])

In [186]:
x=np.arctanh(np.random.rand(20))
x

array([1.19391623e+00, 8.74767056e-01, 3.10130767e-01, 1.24507885e+00,
       9.22581955e-01, 2.13242680e-01, 1.47826637e-01, 6.77168145e-05,
       2.36218747e-01, 1.48317344e+00, 1.78825915e-01, 8.77859903e-01,
       6.46369463e-01, 4.00991583e-01, 2.62774387e-01, 3.81160699e-01,
       2.14985587e-01, 1.03142536e+00, 2.81831973e-01, 1.57140536e+00])

In [194]:
arr2

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [195]:
np.logical_not(arr2) #compute the truth value of not x element wise(equivalent to ~arr)

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False])