In [1]:
import numpy as np

# Boolean Indexing

In [23]:
name=['Bob','Rose','Marley','Mary','Bob','Alex','Robert']
name=np.array(name)
data=np.random.randn(7,4)

In [28]:
data

array([[-1.1577639 ,  0.6622762 , -2.03786036, -0.02018306],
       [ 0.01809167,  0.03803094, -0.25894742,  0.08225325],
       [ 0.02629574,  0.40920595,  0.23988935, -0.18006089],
       [-0.36387224,  0.86822906,  0.39483332,  0.33180869],
       [ 1.35716953,  0.05439917,  0.82907523,  1.49923911],
       [-0.86624078,  0.10560175,  0.41028064,  1.47470524],
       [ 0.84517528, -1.83862262,  0.32566862,  0.3611213 ]])

In [29]:
name=='Bob'

array([ True, False, False, False,  True, False, False])

In [30]:
data[name=='Bob'] #selects all the rows with respect to the index number of True in the name boolean array

array([[-1.1577639 ,  0.6622762 , -2.03786036, -0.02018306],
       [ 1.35716953,  0.05439917,  0.82907523,  1.49923911]])

In [31]:
data[name=='Bob',2:] #applying indexing

array([[-2.03786036, -0.02018306],
       [ 0.82907523,  1.49923911]])

In [32]:
data[name=='Bob',1:3]

array([[ 0.6622762 , -2.03786036],
       [ 0.05439917,  0.82907523]])

In [34]:
data[~(name=='Bob')] #this sign is use to invert the values, displaying all the false values

array([[ 0.01809167,  0.03803094, -0.25894742,  0.08225325],
       [ 0.02629574,  0.40920595,  0.23988935, -0.18006089],
       [-0.36387224,  0.86822906,  0.39483332,  0.33180869],
       [-0.86624078,  0.10560175,  0.41028064,  1.47470524],
       [ 0.84517528, -1.83862262,  0.32566862,  0.3611213 ]])

In [35]:
cond=name=='Bob'

In [36]:
cond

array([ True, False, False, False,  True, False, False])

In [37]:
data[~cond]

array([[ 0.01809167,  0.03803094, -0.25894742,  0.08225325],
       [ 0.02629574,  0.40920595,  0.23988935, -0.18006089],
       [-0.36387224,  0.86822906,  0.39483332,  0.33180869],
       [-0.86624078,  0.10560175,  0.41028064,  1.47470524],
       [ 0.84517528, -1.83862262,  0.32566862,  0.3611213 ]])

In [41]:
mask=(name=='Bob')|(name=='Robert') #appling multiple conditions

In [39]:
mask

array([ True, False, False, False,  True, False,  True])

In [42]:
data[mask]

array([[-1.1577639 ,  0.6622762 , -2.03786036, -0.02018306],
       [ 1.35716953,  0.05439917,  0.82907523,  1.49923911],
       [ 0.84517528, -1.83862262,  0.32566862,  0.3611213 ]])

In [43]:
#eliminating all the negative values
x=data[data<0]

In [44]:
x

array([-1.1577639 , -2.03786036, -0.02018306, -0.25894742, -0.18006089,
       -0.36387224, -0.86624078, -1.83862262])

In [45]:
data[data<0]=0

In [46]:
data

array([[0.        , 0.6622762 , 0.        , 0.        ],
       [0.01809167, 0.03803094, 0.        , 0.08225325],
       [0.02629574, 0.40920595, 0.23988935, 0.        ],
       [0.        , 0.86822906, 0.39483332, 0.33180869],
       [1.35716953, 0.05439917, 0.82907523, 1.49923911],
       [0.        , 0.10560175, 0.41028064, 1.47470524],
       [0.84517528, 0.        , 0.32566862, 0.3611213 ]])

# Fancy Indexing

In [20]:
arr=np.arange(20).reshape(5,4).astype(np.int64)

In [26]:
arr=arr/32

In [23]:
arr.astype(np.int64)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
arr

array([[0.     , 0.03125, 0.0625 , 0.09375],
       [0.125  , 0.15625, 0.1875 , 0.21875],
       [0.25   , 0.28125, 0.3125 , 0.34375],
       [0.375  , 0.40625, 0.4375 , 0.46875],
       [0.5    , 0.53125, 0.5625 , 0.59375]])

In [28]:
arr.astype(np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
for i in range(5):
    arr[i]=i/3

In [37]:
arr

array([[0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        , 1.        ],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333]])

In [38]:
arr[2]

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [39]:
#selecting multiple rows
arr[[2,4]]

array([[0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333]])

In [41]:
#using negative indexing 
arr[[-2,-1,-3]]

array([[1.        , 1.        , 1.        , 1.        ],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667]])

In [44]:
arr=np.arange(32).reshape((8,4))

In [45]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [47]:
arr[[0,3,1,2]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
arr[[1,5,7,2,1],[0,3,1,2,3]] #here it is creating tuples like (1,0),(5,3),(7,1),(2,2) in rows and column of same indexes
#of different arrays

array([ 4, 23, 29, 10,  7])

In [65]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [64]:
arr[[1,5,7,2]][1] #one is the row number
'''
array([[ 4,  5,  6,  7],
       [20, 21, 22, 23], #index no 1
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])'''

array([20, 21, 22, 23])

In [66]:
arr[[1,5,7,2]][:] #getting all values

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [67]:
arr[[1,5,7,2]][:,[0,3]] #it is only getting the column number [0,3] are the column numbers of the sliced index

array([[ 4,  7],
       [20, 23],
       [28, 31],
       [ 8, 11]])

In [70]:
arr[[1,5,7,2]][:,[0,1,3]]

array([[ 4,  5,  7],
       [20, 21, 23],
       [28, 29, 31],
       [ 8,  9, 11]])

In [74]:
arr[[1,5,7,2]][:,[0,3,1]] #you can see that the values of columns are applied to the given column numbers respectively

array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29],
       [ 8, 11,  9]])

# Transposing

In [77]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [79]:
arr.T #converting rows into columns and columns into rows

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [82]:
arr2=np.random.rand(6,3)

In [84]:
arr2=arr2*10

In [85]:
arr2

array([[ 5.47644718, 72.29668049, 11.2163119 ],
       [45.96890938, 23.25108653, 49.8767786 ],
       [55.9551358 , 31.40499651, 60.3781863 ],
       [58.92148252, 98.45366904, 37.47930132],
       [37.51512165, 86.27213377, 39.34324406],
       [52.8589972 ,  5.04820776, 18.09325818]])

In [88]:
np.dot(arr2,arr2.T) #getting dot product of 2 arrays

array([[ 5382.60713569,  2492.15618307,  3254.13291363,  7860.93337314,
         6883.92456835,   857.3877965 ],
       [ 2492.15618307,  5141.44669743,  6313.86628818,  6867.05788216,
         5692.76434786,  3449.68019995],
       [ 3254.13291363,  6313.86628818,  7762.77640876,  8651.82892616,
         7184.01350588,  4208.7094268 ],
       [ 7860.93337314,  6867.05788216,  8651.82892616, 14569.56407683,
        12178.81198838,  4289.66773094],
       [ 6883.92456835,  5692.76434786,  7184.01350588, 12178.81198838,
        10398.15626994,  3130.37883777],
       [  857.3877965 ,  3449.68019995,  4208.7094268 ,  4289.66773094,
         3130.37883777,  3146.92397832]])

In [144]:
arr=np.arange(32).reshape((4,4,2)) #2 arrays 2 rows in each array and 4 columns

In [145]:
arr.transpose()

array([[[ 0,  8, 16, 24],
        [ 2, 10, 18, 26],
        [ 4, 12, 20, 28],
        [ 6, 14, 22, 30]],

       [[ 1,  9, 17, 25],
        [ 3, 11, 19, 27],
        [ 5, 13, 21, 29],
        [ 7, 15, 23, 31]]])

In [146]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [156]:
#you can also pass the tuples to transpose the multi-dimensions array

arr.transpose((1,0,2)) #here the second axes become firs and first axes becomes second

array([[[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]],

       [[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]],

       [[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]],

       [[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]]])

In [157]:
''' This 3d array
0,1   8,9    16,17   24,25
2,3   10,11  18,19   26,27
4,5   12,13  20,21   28,29
6,7   14,15  22,23   30,31

converted into

0,1    2,3    4,5    6,7
8,9    10,11  12,13  14,15
16,17  18,19  20,21  22,23
23,25  26,27  28,29  30,31

'''


' This 3d array\n0,1   8,9    16,17   24,25\n2,3   10,11  18,19   26,27\n4,5   12,13  20,21   28,29\n6,7   14,15  22,23   30,31\n\nconverted into\n\n0,1    2,3    4,5    6,7\n8,9    10,11  12,13  14,15\n16,17  18,19  20,21  22,23\n23,25  26,27  28,29  30,31\n\n'

In [149]:
arr2

array([[ 5.47644718, 72.29668049, 11.2163119 ],
       [45.96890938, 23.25108653, 49.8767786 ],
       [55.9551358 , 31.40499651, 60.3781863 ],
       [58.92148252, 98.45366904, 37.47930132],
       [37.51512165, 86.27213377, 39.34324406],
       [52.8589972 ,  5.04820776, 18.09325818]])

In [150]:
arr2.transpose()

array([[ 5.47644718, 45.96890938, 55.9551358 , 58.92148252, 37.51512165,
        52.8589972 ],
       [72.29668049, 23.25108653, 31.40499651, 98.45366904, 86.27213377,
         5.04820776],
       [11.2163119 , 49.8767786 , 60.3781863 , 37.47930132, 39.34324406,
        18.09325818]])

In [151]:
arr2.transpose(1,0)

array([[ 5.47644718, 45.96890938, 55.9551358 , 58.92148252, 37.51512165,
        52.8589972 ],
       [72.29668049, 23.25108653, 31.40499651, 98.45366904, 86.27213377,
         5.04820776],
       [11.2163119 , 49.8767786 , 60.3781863 , 37.47930132, 39.34324406,
        18.09325818]])

In [161]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [193]:
#swapaxes method, it returns the view but donot make copy
arange=arr.swapaxes(1,2) 
arange2=arr.swapaxes(0,2)
arange3=arr.swapaxes(0,1)
arange4=arr.swapaxes(2,1)
arange5=arr.swapaxes(2,0)

In [195]:
arange2
#(2,1)=(1,2)
#(2,0)=(0,2)

array([[[ 0,  8, 16, 24],
        [ 2, 10, 18, 26],
        [ 4, 12, 20, 28],
        [ 6, 14, 22, 30]],

       [[ 1,  9, 17, 25],
        [ 3, 11, 19, 27],
        [ 5, 13, 21, 29],
        [ 7, 15, 23, 31]]])

In [166]:
arange.swapaxes(1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [167]:
arange.swapaxes(0,1)

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23],
        [25, 27, 29, 31]]])