In [2]:
import numpy as np

In [4]:
#as numpy is 10 to 100 times faster then tradational list, lets compare their computational timings
arr=np.arange(1000)
ls=list(range(1000))


In [5]:
%time for _ in range(10): arr2=arr*2

CPU times: user 726 µs, sys: 140 µs, total: 866 µs
Wall time: 41.9 ms


In [6]:
%time for _ in range(10): ls2=[x*2 for x in ls]

CPU times: user 1.31 ms, sys: 0 ns, total: 1.31 ms
Wall time: 2.01 ms


#  python ndarray

In [14]:
data=np.random.randn(2,3)
data

array([[-1.19246902, -0.04294846,  2.77422596],
       [ 0.17015187,  0.25284614, -0.25108605]])

In [15]:
#Mathematical operations on data

In [16]:
data+data

array([[-2.38493804, -0.08589692,  5.54845192],
       [ 0.34030374,  0.50569228, -0.50217209]])

In [17]:
data*19

array([[-22.65691136,  -0.81602073,  52.71029323],
       [  3.23288549,   4.8040767 ,  -4.77063488]])

In [18]:
data/data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#getting shape and type of the ndarray
data.shape #it gives value in tuple format

(2, 3)

In [22]:
data.dtype

dtype('float64')

In [25]:
data1=[1,0.2322,3,-45,'karachi']
x=np.array(data1)
x

array(['1', '0.2322', '3', '-45', 'karachi'], dtype='<U32')

In [33]:
data1=['a','f','e','t','x']
x=np.array(data1)
x.shape

(5,)

In [34]:
#creating multi-dimentional array
data1=[[1,2,3,4],[2,5,1,5],[1,2,4,2],[1,2,3,4]]
x=np.array(data1)
print(x)

[[1 2 3 4]
 [2 5 1 5]
 [1 2 4 2]
 [1 2 3 4]]


In [35]:
#getting the dimension of the array
x.ndim #2 means 2 dimesion

2

In [36]:
x.shape #returning into rows and columns

(4, 4)

In [37]:
x.dtype

dtype('int64')

# other ways to create arrays

In [45]:
print(np.zeros(10)) #creates 1d arrays of zero value
print(np.zeros((3,4))) #creates 2d arrays of zero value
print(np.zeros((3,4,2))) #creates 3d arrays of zeros value
#the 3d is creating 3 arrays inside an array having 4 rows and 2 columns of each array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [47]:
#creating with np.ones
print(np.ones(5))
print(np.ones((2,3)))
print(np.ones((3,2,4)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [52]:
#creating with np.empty
#it returns the garbage values in the array
print(np.empty(4))
print(np.empty((4,2)))
print(np.empty((3,4,2)))

[6.94355005e-310 6.94355817e-310 6.94355842e-310 6.94355851e-310]
[[ 1.75376071e-316  5.61139431e+199]
 [ 2.04719253e+190  2.20735928e+214]
 [-5.53423737e+125  8.64326571e+189]
 [-2.90091490e+127  1.17075772e+214]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [68]:
a=[[132],[42]]
x=np.asarray(a) #converts input into an array, do not copt ifthe input is already an ndarray 
y=np.array(a) #creates an array into ndarray
print(x)
print(y)

[[132]
 [ 42]]
[[132]
 [ 42]]


In [70]:
#the arange method
x=np.arange(5) #creates array with the range specified
print(x)

[0 1 2 3 4]


In [73]:
#creating 2d array with arange
x=np.arange(10).reshape(5,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [77]:
#creating 3d array with arange
x=np.arange(30).reshape(5,3,2) #having 5 internal arrays with 3 rows and 2 columns
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


In [85]:
#ones_like method
np.ones_like(x) #converts the input into ones getting the same dimension of the array
#you cannot pass multi-dimension array into the array exp np.ones([[2,3],[2,3]]) or np.ones(x)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [88]:
#np.zeros_like method 
np.zeros_like(x) #same as np.ones_like just creating 0 values instead of 1

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [93]:
#np.empty_like
np.empty_like(x) #same working as ones_like and zeros_like just creating garbage values instead of zeros and ones

array([[[           37423232,            26395072],
        [                  0,                   0],
        [    140535624892416, 7235419174270214779]],

       [[7077748991036897826, 3775813309621757241],
        [3919088475209623092, 3846691347548484406],
        [8319593459584558646, 4189022123868451429]],

       [[7881702260482471202, 8319104481852400229],
        [3991915752791633769, 3774633538748757302],
        [3618700803217580594, 7377232873766924854]],

       [[3180212246033949237, 8104636957536251170],
        [7162263158163907173, 8462656716707034229],
        [7311068618034541413, 2466321603649696626]],

       [[7017771692297694773, 3544388029326189940],
        [6066686442303663417, 3832908753724387889],
        [6500727470607643182,     140539870608674]]])

In [109]:
#np.full
print(np.full(10,4))
print('-----')
print(np.full([2,3],19))
print('---------')
print(np.full([2,3,4],5)) #np.full creates 3d array with same values as given in the argument
#with 2 arrays and 3 rows and 4 columns

[4 4 4 4 4 4 4 4 4 4]
-----
[[19 19 19]
 [19 19 19]]
---------
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [112]:
#np.full_like
print(np.full_like(x,4)) #same as ones like and other, it just takes 1 extra argument which is the value
#to fill the arrays with, otherwise it will return an error 

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]


In [126]:
np.eye(5,5) #it returns only 2d identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
np.eye(10,10,2) #where 2 is the index number 2 starts the identity

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [131]:
#changing data type of arrays
print(np.array([1,2,3,4,5],dtype=np.float64))

[1. 2. 3. 4. 5.]


In [132]:
print(np.array([1.2,3.2,4.2,4.2],dtype=np.int64))

[1 3 4 4]


In [4]:
#changing dtype explicitly 
arr=np.array([1,2,3,4,5,6])
arr.dtype

dtype('int64')

In [7]:
arr.astype(np.int32)

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [8]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5., 6.])

In [19]:
arr2=np.array(['12','23','42','42'],dtype=(np.string_))
print(arr2)
x=arr2.astype(float)
x

[b'12' b'23' b'42' b'42']


array([12., 23., 42., 42.])

In [22]:
arr3=np.array([1,2,3,4,5],dtype=(arr2.dtype))

In [23]:
arr3

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S2')

In [24]:
arr3=np.array([1,3,4,2,1],dtype=(x.dtype))
arr3

array([1., 3., 4., 2., 1.])

In [25]:
arr3=np.array([1,2,3,4,5],dtype=(np.uint32))

In [26]:
arr3

array([1, 2, 3, 4, 5], dtype=uint32)

#  Arithematic Operartions, are also known as Vectorizing by Numpy Users

In [47]:
arr=np.arange(20,40).reshape(5,4)
arr

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [48]:
x=arr+arr

In [49]:
x

array([[40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62],
       [64, 66, 68, 70],
       [72, 74, 76, 78]])

In [50]:
arr*4

array([[ 80,  84,  88,  92],
       [ 96, 100, 104, 108],
       [112, 116, 120, 124],
       [128, 132, 136, 140],
       [144, 148, 152, 156]])

In [51]:
arr/(arr*3)

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [52]:
arr**4

array([[ 160000,  194481,  234256,  279841],
       [ 331776,  390625,  456976,  531441],
       [ 614656,  707281,  810000,  923521],
       [1048576, 1185921, 1336336, 1500625],
       [1679616, 1874161, 2085136, 2313441]])

In [67]:
arr2=np.arange(20,60,2).reshape(5,4)
print(arr2,'----',sep='\n')
print(arr)

[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]
----
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [68]:
arr<arr2

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
y=arr2>arr
y.dtype

dtype('bool')

# Slicing of Arrays

In [71]:
arr=np.array([1,2,3,4,5,6,76,43,1,3,13,3,1,2,3,41,5,4,3,2,1])

In [75]:
x=arr[5:8]
x

array([ 6, 76, 43])

In [80]:
#both the values are changing due to pass by reference
x[1]=154267842
x

array([        6, 154267842,        43])

In [78]:
arr

array([        1,         2,         3,         4,         5,         6,
       154267842,        43,         1,         3,        13,         3,
               1,         2,         3,        41,         5,         4,
               3,         2,         1])

In [81]:
x[:]=43
x

array([43, 43, 43])

In [82]:
arr

array([ 1,  2,  3,  4,  5, 43, 43, 43,  1,  3, 13,  3,  1,  2,  3, 41,  5,
        4,  3,  2,  1])

In [83]:
#slicing through pass by value
x=arr[5:8].copy()
x

array([43, 43, 43])

In [84]:
x[:]=99
x

array([99, 99, 99])

In [85]:
arr

array([ 1,  2,  3,  4,  5, 43, 43, 43,  1,  3, 13,  3,  1,  2,  3, 41,  5,
        4,  3,  2,  1])

# Slicing higher dimensional array 

In [87]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[11,21,31,41]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 21, 31, 41]])

In [88]:
arr2d[2] #getting the 2nd index value of the outer array

array([11, 21, 31, 41])

In [90]:
arr2d[1][2] #getting the value of 2nd index value of internal array at 1st index

7

In [99]:
arr2d[2:3] 

array([[11, 21, 31, 41]])

In [100]:
arr2d=np.arange(1,21).reshape(5,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [103]:
#getting value through rows and column
arr2d[2,1] #retreiving the value at 2nd row and 1st column of it

10

In [104]:
#3D slicing
arr3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])

In [105]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [109]:
arr3d.shape #showing 3arrays with 2 rows and 4 columns

(3, 2, 4)

In [110]:
arr3d.ndim

3

In [111]:
arr3d[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
arr3d[0][1]

array([5, 6, 7, 8])

In [113]:
arr3d[0][1][2]

7

In [116]:
arr3d[2][0][3]

20

In [117]:
arr_2d=arr3d[0].copy()

In [122]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
arr_2d.dtype

dtype('int64')

In [120]:
arr3d[0]=42

In [121]:
arr3d

array([[[42, 42, 42, 42],
        [42, 42, 42, 42]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [124]:
arr3d[0]=arr_2d

In [125]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [127]:
arr3d[1,0] #returning all values lying at the 1st index of the 1st index array 

array([ 9, 10, 11, 12])

In [130]:
arr2d[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
arr2d[:1]

array([[1, 2, 3, 4]])

In [132]:
arr2d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [133]:
arr2d[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [134]:
arr2d[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [135]:
arr2d[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [137]:
#passing multiple slices
arr2d[1,3]

8

In [138]:
arr2d[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [143]:
arr2d[2:4,1:4]

array([[10, 11, 12],
       [14, 15, 16]])

In [144]:
arr2d[:,:1]

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]])

In [146]:
#assigning values through slicing
arr2d[0:4,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [147]:
arr2d[0:4,0:3]=199

In [148]:
arr2d

array([[199, 199, 199,   4],
       [199, 199, 199,   8],
       [199, 199, 199,  12],
       [199, 199, 199,  16],
       [ 17,  18,  19,  20]])